export const vehicleActionTypes = {
  GET_USER_VEHICLES_START: 'GET_USER_VEHICLES_START',
  GET_USER_VEHICLES_SUCCESS: 'GET_USER_VEHICLES_SUCCESS',
  GET_USER_VEHICLES_FAILURE: 'GET_USER_VEHICLES_FAILURE',
  ADD_VEHICLE_START: 'ADD_VEHICLE_START',
  ADD_VEHICLE_SUCCESS: 'ADD_VEHICLE_SUCCESS',
  ADD_VEHICLE_FAILURE: 'ADD_VEHICLE_FAILURE',
  UPLOAD_VEHICLE_IMAGE_START: 'UPLOAD_VEHICLE_IMAGE_START',
  UPLOAD_VEHICLE_IMAGE_SUCCESS: 'UPLOAD_VEHICLE_IMAGE_SUCCESS',
  UPLOAD_VEHICLE_IMAGE_FAILURE: 'UPLOAD_VEHICLE_IMAGE_FAILURE',
  ADD_SERVICE_HISTORY_START: 'ADD_SERVICE_HISTORY_START',
  ADD_SERVICE_HISTORY_SUCCESS: 'ADD_SERVICE_HISTORY_SUCCESS',
  ADD_SERVICE_HISTORY_FAILURE: 'ADD_SERVICE_HISTORY_FAILURE',
};
